name: Run Tests

on: [push]

env:
  DATABASE_URL: mysql://user:password@localhost:3306/awesomepower

jobs:
  unit-integration:
    name: Vitest unit/integration tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: awesomepower
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm db:reset && pnpm db:seed

      - name: Instrument src
        run: |
          cp -r ./src ./src-tmp
          pnpm nyc instrument src --in-place

      - run: pnpm build --no-lint

      - run: pnpm nyc pnpm start &

      - run: pnpm vitest:run

      - name: Replace src with true source
        if: ${{ always() }}
        run: |
          rm -rf ./src
          mv ./src-tmp ./src

      - name: Upload unit test coverage to Coveralls
        if: ${{ always() }}
        uses: coverallsapp/github-action@1.1.3
        with:
          flag-name: unit
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./.nyc/coverage/lcov.info
          parallel: true

      # This replaces the unit test code coverage at ./.nyc/coverage/lcov.info
      # with the server code coverage, for the integration tests
      - name: Stop Next.js server
        run: kill $(lsof -t -i:3000)
        if: ${{ always() }}

      - name: Upload integration test coverage to Coveralls
        if: ${{ always() }}
        uses: coverallsapp/github-action@1.1.3
        with:
          flag-name: integration
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./.nyc/coverage/lcov.info
          parallel: true

  component:
    name: Cypress component tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'pnpm'

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/.github/workflows/test.yml') }}
          restore-keys: ${{ runner.os }}-

      - run: pnpm install

      - name: Instrument src
        run: |
          mkdir tmp
          cp -r ./src ./tmp/src
          pnpm nyc instrument src --in-place

      - name: Cypress component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: pnpm cypress run-ct

      - name: Replace src with true source
        if: ${{ always() }}
        run: |
          rm -rf ./src
          mv ./tmp/src ./src

      - name: Upload to Coveralls
        if: ${{ always() }}
        uses: coverallsapp/github-action@1.1.3
        with:
          flag-name: component
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./.nyc/coverage/lcov.info
          parallel: true

  e2e:
    name: Cypress end-to-end tests
    runs-on: ubuntu-latest

    strategy:
      # https://github.com/cypress-io/github-action#parallel
      fail-fast: false
      matrix:
        containers: [1, 2]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: awesomepower
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'pnpm'

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/.github/workflows/test.yml') }}
          restore-keys: ${{ runner.os }}-

      - run: pnpm install

      - name: Instrument src
        run: |
          mkdir tmp
          cp -r ./src ./tmp/src
          pnpm nyc instrument src --in-place

      - name: Cypress end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm build --no-lint
          start: pnpm start
          wait-on: http://localhost:3000
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace src with true source
        if: ${{ always() }}
        run: |
          rm -rf ./src
          mv ./tmp/src ./src

      - name: Upload to Coveralls
        if: ${{ always() }}
        uses: coverallsapp/github-action@1.1.3
        with:
          flag-name: e2e-${{ matrix.containers }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./.nyc/coverage/lcov.info
          parallel: true

  finalize-coveralls:
    name: Finalize Coveralls coverage
    if: ${{ always() }}
    needs: [unit-integration, component, e2e]
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
