name: test

on:
  - push

env:
  DATABASE_URL: mysql://awesomepower:awesomepower@localhost:3306/awesomepower
  NODE_ENV: production

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: awesomepower
          MYSQL_PASSWORD: awesomepower
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: awesomepower
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
        env:
          NODE_ENV: development

      - run: pnpm lint

      - run: pnpm typecheck

      - run: pnpm db:reset

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm build
          start: pnpm start
          wait-on: http://localhost:3000
