name: Update Plans

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-plans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1
          run_install: true
        env:
          NODE_ENV: development

      - run: pnpm job -- updatePlans
