name: Update Plans

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-plans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.0.1

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'pnpm'

      - run: pnpm install

      - name: Set up Google credentials
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - run: pnpm prisma generate && pnpm db:seed
        env:
          APP_ENV: production
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

      - run: pnpm admin:updatePlans
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
