name: Update Plans

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-plans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.11
          run_install: true

      - name: Set up Google credentials
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - run: pnpm db:seed
        env:
          APP_ENV: production
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

      - run: pnpm admin:updatePlans
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
